package main

const page = `<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="stylesheet" href="/app.css"><title>LitraDock · Go migration candidate</title><body><main><h1>LitraDock</h1><p>Isolated Go migration candidate · login and PubMed search</p><p>Acquisition, original downloads, exports and recovery remain available on the current pilot. This candidate does not modify those originals.</p><p id="operator"></p><form id="login"><label>Login <input name="login" autocomplete="username" required></label><label>Password <input name="password" type="password" autocomplete="current-password" required></label><button>Sign in</button></form><section id="work" hidden><button id="logout">Sign out</button><h2>Your libraries</h2><select id="libraries" aria-label="Library"></select><form id="library"><label>New library name <input name="name" maxlength="120" required></label><button>Create library</button></form><h2>Search PubMed</h2><form id="search"><label>Query <input name="query" maxlength="2000" required></label><label>Result limit <input name="limit" type="number" min="1" max="100" value="10" required></label><button>Search</button></form><p>Queries and identifiers are sent to NCBI. Public metadata does not imply full-text reuse permission. NCBI does not endorse this service. <a href="https://www.ncbi.nlm.nih.gov/home/about/policies/">NCBI policies and disclaimer</a></p><section id="results" aria-label="Search results"></section></section><p role="status" id="status" aria-live="polite"></p></main><script src="/app.js"></script></body></html>`
const script = `const $=s=>document.getElementById(s);let csrf='',generation=0;

function cleared(){generation++;csrf='';$('work').hidden=true;$('login').hidden=false;$('results').replaceChildren();$('libraries').replaceChildren();runs.replaceChildren();moreRows.hidden=true;historyOffset=0;historyRequest++;previousRuns.disabled=true;nextRuns.disabled=true}
async function api(path,body){const g=generation;const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json','X-CSRF':csrf},body:body===undefined?undefined:JSON.stringify(body)});if(g!==generation)throw Error('Session changed.');if(r.status===401){cleared();throw Error('Please sign in.')}const text=await r.text();if(g!==generation)throw Error('Session changed.');let data=text?JSON.parse(text):{};if(!r.ok)throw Error(data.error||'Request unavailable (HTTP '+r.status+').');return data}
function status(t){$('status').textContent=t}async function libraries(){const g=generation;const data=await api('/api/libraries');if(g!==generation)return;$('libraries').replaceChildren(...data.items.map(x=>new Option(x.name,x.library_id)));await loadRuns()}
$('login').onsubmit=async e=>{e.preventDefault();cleared();const loginGeneration=generation;try{const f=new FormData(e.target),d=await api('/api/login',{login:f.get('login'),password:f.get('password')});if(loginGeneration!==generation)return;generation++;csrf=d.csrf;e.target.reset();$('login').hidden=true;$('work').hidden=false;await libraries();status('Signed in.')}catch(e){status(e.message)}};
$('logout').onclick=async()=>{try{await api('/api/logout',{});cleared();status('Signed out.')}catch(e){status(e.message)}};
$('library').onsubmit=async e=>{e.preventDefault();try{await api('/api/libraries',{value:new FormData(e.target).get('name')});await libraries();e.target.reset();status('Library created.')}catch(e){status(e.message)}};
$('search').onsubmit=async e=>{e.preventDefault();const library=$('libraries').value;if(!library){status('Create or choose a library first.');return}const g=generation;try{const f=new FormData(e.target),run=await api('/api/libraries/'+library+'/search',{query:f.get('query'),limit:Number(f.get('limit'))});status('Search queued; waiting for source metadata.');$('results').replaceChildren();for(let n=0;n<100;n++){await new Promise(r=>setTimeout(r,1000));if(g!==generation)return;const current=await api('/api/libraries/'+library+'/runs/'+run.id),item=current.run;if(!item)continue;if(item.state==='queued'||item.state==='running')continue;status(item.state+': '+(item.reason||('Retrieved '+item.fetched+' of '+item.total)));if(item.state!=='complete'&&item.state!=='partial')return;const rows=current;render(rows.records);await loadRuns();return}status('Search remains unfinished; inspect the saved run before submitting again.')}catch(e){status(e.message)}};

function render(articles){for(const a of articles){const card=document.createElement('article');const title=document.createElement('h3');title.textContent=a.Title;card.append(title);const details=document.createElement('p');details.textContent=a.Authors+' · '+a.Year+' · '+a.Journal;card.append(details);const ids=document.createElement('p');ids.textContent='PMID '+a.Pmid+' · PMCID '+a.Pmcid+' · DOI '+a.Doi;card.append(ids);if(a.DoiLinkState==='unsupported_path_segments'){const note=document.createElement('p');note.textContent='DOI link unavailable: this identifier contains unsupported path segments. The original DOI is preserved above.';card.append(note)}for(const [label,target]of[['PubMed',a.OriginalUri],['PMC',a.PmcUri],['DOI',a.DoiUri]]){if(!target)continue;const u=new URL(target);if(u.protocol!=='https:'||!['pubmed.ncbi.nlm.nih.gov','pmc.ncbi.nlm.nih.gov','doi.org'].includes(u.hostname))continue;const link=document.createElement('a');link.textContent=label+' ';link.href=u.href;link.target='_blank';link.rel='noopener noreferrer';card.append(link)}$('results').append(card)}}
const history=document.createElement('section'),historyTitle=document.createElement('h2'),runs=document.createElement('select'),openRun=document.createElement('button'),moreRows=document.createElement('button');historyTitle.textContent='Saved searches';runs.setAttribute('aria-label','Saved search');openRun.textContent='Open saved search';moreRows.textContent='Next 100 records';moreRows.hidden=true;history.append(historyTitle,runs,openRun,moreRows);$('search').after(history);let rowOffset=0,historyOffset=0,historyRequest=0;const previousRuns=document.createElement('button'),nextRuns=document.createElement('button');previousRuns.textContent='Previous saved searches';nextRuns.textContent='Next saved searches';previousRuns.disabled=true;nextRuns.disabled=true;history.append(previousRuns,nextRuns);previousRuns.onclick=()=>{historyOffset=Math.max(0,historyOffset-100);loadRuns().catch(e=>status(e.message))};nextRuns.onclick=()=>{historyOffset+=100;loadRuns().catch(e=>status(e.message))};
async function loadRuns(){const g=generation,request=++historyRequest,library=$('libraries').value;runs.replaceChildren();moreRows.hidden=true;previousRuns.disabled=true;nextRuns.disabled=true;if(!library)return;const data=await api('/api/libraries/'+library+'?offset='+historyOffset);if(g!==generation||request!==historyRequest||library!==$('libraries').value)return;runs.replaceChildren(...data.runs.map(x=>new Option(x.input+' · '+x.state,x.run_id)));historyTitle.textContent='Saved searches: '+(data.runs.length?historyOffset+1:0)+'–'+(historyOffset+data.runs.length)+' of '+data.totals.runs;previousRuns.disabled=historyOffset===0;nextRuns.disabled=historyOffset+data.runs.length>=data.totals.runs;}
async function saved(){const g=generation;if(!runs.value)return;try{const data=await api('/api/libraries/'+$('libraries').value+'/runs/'+runs.value+'?offset='+rowOffset);if(g!==generation)return;$('results').replaceChildren();render(data.records);moreRows.hidden=rowOffset+data.records.length>=data.total;status(data.run.state+': '+(data.run.reason||'')+' Showing saved records '+(data.records.length?rowOffset+1:0)+'–'+(rowOffset+data.records.length)+' of '+data.total+'.')}catch(e){status(e.message)}}
openRun.onclick=()=>{rowOffset=0;saved()};moreRows.onclick=()=>{rowOffset+=100;saved()};$('libraries').onchange=()=>{historyOffset=0;loadRuns().catch(e=>status(e.message));$('results').replaceChildren()};
api('/service-info').then(x=>{$('operator').textContent=x.operatorName+' · '+x.contact+' · '+x.retention+' · Expires '+x.expiresAt}).catch(e=>status(e.message));`

const styles = `[hidden]{display:none!important}body{font:16px system-ui;background:#f5f7fa;color:#172739;margin:0}main{max-width:960px;padding:24px;margin:auto}form{display:flex;gap:12px;flex-wrap:wrap;margin:20px 0}label{display:grid;gap:5px}input,select,button{font:inherit;padding:10px;border:1px solid #63788e;border-radius:6px;max-width:100%;box-sizing:border-box}button{background:#123f69;color:white;cursor:pointer}article{background:white;border:1px solid #bdcad6;border-radius:8px;padding:16px;margin:12px 0}a{color:#075eaa}#status{white-space:pre-wrap}`
