<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <DefineConstants>$(DefineConstants);MODERN_SQLITE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Remove="Microsoft.NETFramework.ReferenceAssemblies" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <Compile Include="../LitraDock.Core/*.cs" Link="Core/%(Filename)%(Extension)" />
  </ItemGroup>
</Project>
