<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Remove="Microsoft.NETFramework.ReferenceAssemblies" />
    <ProjectReference Include="../../src/LitraDock.Hosted/LitraDock.Hosted.csproj" />
  </ItemGroup>
</Project>
